config/routes.rb
Rails.application.routes.draw do
  
  get 'sub/top'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "homes#top"
  get "about" => "homes#about" 
  
  resources :users ,only:[:index,:show,:edit,:update]
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  validates :title ,presence: true
  validates :body ,presence: true ,length:{maximum: 200}
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books ,dependent: :destroy
  attachment :profile_image
  
  validates :name ,uniqueness: true
  validates :introduction , length:{maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user! ,except:[:top,:about]

  protected
  
  def after_sign_in_path_for(resource)
   user_path(current_user.id) # ログイン後に遷移するpathを設定
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :ensure_correct_user,only:[:edit,:update,:destroy]
  
  def create
    book = Book.new(book_params)
    book.user_id = current_user.id
    book.save
    redirect_to book_path(book.id)
  end
  
  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end
  
  def show
    @user = current_user
    @newbook = Book.new
    @book = Book.find(params[:id])
  end
  
  def edit
    @book =Book.find(params[:id])
  end
  
  def update
    @book =Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  
  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
  
  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
    
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :ensure_correct_user,only:[:edit,:update]

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
    
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
    
  end
  
  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to users_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<tbody>
    <tr>
      <td><%=link_to user_path(book.user_id) do %>
        <%= attachment_image_tag book.user, :profile_image,:fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg",size:"50x50"%><br/>
        <%= book.user.name %>
        <%end%>
      </td>
      <td><%=link_to book_path(book.id) do %>
        <%= book.title %><%end%>
      </td>
      <td><%= book.body %></td>
      
      <% if book.user == current_user %>
        <td><%= link_to "Edit",edit_book_path(book.id) ,class:"btn btn-success btn-sm"%></td>
        <td><%= link_to "Destroy",book_path(book.id) ,method: :delete,class:"btn btn-danger btn-sm"%></td>
      <%end%>
    </tr>
</tbody>

app/views/books/_new.html.erb
<h2 class="pt-3">New book</h2>

<%= form_with model:book ,local: true do |f|%>
  <div class="pb-3">
    <%= f.label :title %><br/>
    <%= f.text_field :title ,class:"form-control" %>
  </div>
  <div class="pb-3">
    <%= f.label :opinion %><br>
    <%= f.text_area :body ,class:"form-control" %>
  </div>
  <div>
    <%= f.submit "Create Book" ,class:"btn btn-success"%>
  </div>
<%end%>

app/views/books/edit.html.erb
<div class="row mx-auto">
  <div class="col-md-7 mx-auto">
  <h2>Editing Book</h2>
  
  <%= form_with model: @book , local: true do |f| %>
    <div class="mb-3">
      <%= f.label :title %>
      <%= f.text_field :title,class:"form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :opinion %>
      <%= f.text_area:body,class:"form-control" %>
    </div>
    <div class="mb-3">
      <%= f.submit "Update Book",class:"btn btn-success btn-md" %>
    </div>
  <%end%>
  
  <%= link_to "show",book_path(@book) %><span>|</span>
  <%= link_to "back",books_path %>
  
  </div>
</div>

app/views/books/index.html.erb
<div class=row>
  <div class="col-md-4">

    <!--userプロフィール-->
    <%= render "users/profile", user:@user %>

    <!--newbook-->
    <%= render "books/new", book:@book %>
  </div>

  <div class="col-md-7 ml-auto">
    <h2>Books</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <%= render @books %>
    </table>
  </div>
</div>

app/views/books/show.html.erb
<div class=row>
  <div class="col-md-4">
    
    <!--userプロフィール-->
    <%= render "users/profile", user:@user %>
    
    <!--newbook-->
    <%= render "books/new", book:@book %>
  </div>
  
  <div class="col-md-7 ml-auto">
    <h2>Book detail</h2>
    <table class="table table-white">
      <%= render @book %>
    </table>
  </div>
  
</div>
    

app/views/homes/about.html.erb
<div class="row">
  <div class="col-md-8 mx-auto">
    <h1 class="text text-center">welcome to <i class="fas fa-book-dead"></i><span class="text-bord">Bookers</span>!!</h1>
  
  </div>
</div>

app/views/homes/top.html.erb
<div class="row">
  <div class="col-md-8 mx-auto">
    <h1 class="text text-center">welcome to <i class="fas fa-book-dead"></i><span class="text-bord">Bookers</span>!!</h1>
  
    <p>In <i class="fas fa-book"></i><span>Bookers</span>, </p>
    <p>you canshare and exchange your opinions , inpressions , and emotions,</p>
    <p>about various books!</p>
  </div>
</div>

<div class="row">
  <div class="col-md-6 mx-auto">
    <%= link_to "Log in" ,new_user_session_path ,class:"btn btn-info btn-block "%>
    <%= link_to "Sign up" ,new_user_registration_path ,class:"btn btn-success btn-block "%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <!--メインロゴ-->
          <%= link_to "Bookers",root_path ,class:"navbar-brand p-3 text-light"%>

          <!--メニューボタン-->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Dropdown" aria-controls="Dropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!--ボタンの中-->
          <div class="collapse navbar-collapse" id="Dropdown">
            <ul class="navbar-nav ml-auto text-light">

              <% if user_signed_in? %>

                <li><%= link_to root_path ,class:"nav-link" do %>
                  <i class="fas fa-house-user"></i><span>Home</span><%end%>
                </li>
                <li><%= link_to books_path ,class:"nav-link" do %>
                  <i class="fas fa-book-dead"></i><span>Book</span><%end%>
                </li>
                <li><%= link_to users_path ,class:"nav-link" do %>
                  <i class="fas fa-user-friends"></i><span>User</span><%end%>
                </li>
                <li><%= link_to destroy_user_session_path ,method: :delete, class:"nav-link" do %>
                  <i class="fas fa-sign-out-alt"></i><span>Log out</span><%end%>
                </li>

              <%else%>

                <li><%= link_to root_path ,class:"nav-link" do %>
                  <i class="fas fa-house-user"></i><span>Home</span><%end%>
                </li>
                <li><%= link_to about_path ,class:"nav-link" do %>
                  <i class="fas fa-eject"></i><span>About</span><%end%>
                </li>
                <li><%= link_to new_user_registration_path ,class:"nav-link" do %>
                  <i class="fas fa-user-plus"></i><span>Sign up</span><%end%>
                </li>
                <li><%= link_to new_user_session_path ,class:"nav-link" do %>
                  <i class="fas fa-sign-in-alt"></i><span>Log in</span><%end%>
                </li>

              <%end%>
            </ul>


          </div>

        </div>
      </nav>
    </header>


    <main>
      <div class="container mx-auto pt-3">

          <%= yield %>

      </div>
    </main>


    <footer class="text text-center py-3">
      <p>CopyRight Infratop.inc</p>
    </footer>

  </body>
</html>

app/views/users/_profile.html.erb
<h2>User info</h2>


<%= attachment_image_tag user ,:profile_image,:fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg",size:"50x50" %>

<table class="table">
  <tbody>
    <tr>
      <th>name<th>
      <th><%= user.name %></th>
    <tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>

<%if current_user == user %>
  <%= link_to "" ,edit_user_path(user) ,class:"btn btn-outline-secondary btn-block btn-md fas fa-user-edit" %>
<%end%>

app/views/users/edit.html.erb
<div class="row mx-auto">
  <div class="col-md-7 mx-auto">
    <h2>User info</h2>

    <%= form_with model: @user , local: true do |f| %>
      <div class="mb-3">
        <%= f.label :name %>
        <%= f.text_field :name,class:"form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :image %><br/>
        <%= f.attachment_field :profile_image %>
      </div>
      <div class="mb-3">
        <%= f.label :introduction %>
        <%= f.text_area:introduction,class:"form-control" %>
      </div>
      <div class="mb-3">
        <%= f.submit "Update User",class:"btn btn-success btn-md" %>
      </div>
    <%end%>

  </div>
</div>

app/views/users/index.html.erb
<div class=row>
  <div class="col-md-4">
    
    <!--userプロフィール-->
    <%= render "users/profile", user:@user %>
    
    <!--newbook-->
    <%= render "books/new", book:@book %>
  </div>
  
  <div class="col-md-7 ml-auto">
    <h2>Users</h2>
    
    <table class="table table-white">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image,:fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg",size:"50x50"%><br/>
          </td>
          <td><%= user.name %></td>
          <td><%= link_to "Show",user_path(user.id) %></td>
        </tr>
        <%end%>
      </tbody>

    </table>

  </div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>